AWSTemplateFormatVersion: "2010-09-09"
Description: stack Lambda Function for consolidation api results.
# create parameters
Parameters:
  pBucketName:
    Type: String
    Default: bkt-teste-paulo #bkt-api-viavarejo-uat
    Description: Bucket name
  pFunctionName:
    Type: String
    Default: turing-uat-scoreapi-lbd-report
    Description: Function name
  pQueueName:
    Type: String
    Default: turing-uat-scoreapi-sqs-report
    Description: SQS Queue name
  pLayerName:
    Type: String
    Default: turing-uat-scoreapi-lbd-layer-report
    Description: SQS Queue name
Resources:
  # create sqs queue
  rSQSQueue:
    Type: AWS::SQS::Queue
    Properties:
      MessageRetentionPeriod: 1209600
      QueueName: !Ref pQueueName
      VisibilityTimeout: 43200
  # create lambda layer
  rLambdaLayer:
    Type: AWS::Lambda::LayerVersion
    Properties:
      CompatibleRuntimes:
        - python3.6
        - python3.7
        - python3.8
      Content:
        S3Bucket: !Ref pBucketName
        S3Key: setup/consolidacao_results_api/lambda/dependencies_lambda-get-results-api.zip
      Description: !Sub Dependencies for ${pFunctionName}
      LayerName: !Ref pLayerName
  # create lambda function
  rLambdaFunction:
    Type: AWS::Lambda::Function
    Properties:
      Code:
        S3Bucket: !Ref pBucketName
        S3Key: setup/consolidacao_results_api/lambda/lambda_get_results_api.zip
      Description: Function to consolidate API requests / returns
      FunctionName: !Ref pFunctionName
      Handler: lambda_function.lambda_handler
      Layers:
        - !Ref rLambdaLayer
      MemorySize: 128
      Role: arn:aws:iam::313558459655:role/service-role/L01-Start-LabTuring-role-silexq2e
      Runtime: python3.7
      Timeout: 5
  # create lambda version
  rLambdaVersion:
    Type: AWS::Lambda::Version
    Properties:
      FunctionName: !GetAtt rLambdaFunction.Arn
  # create lambda destination on failure
  rLambdaDestinationError:
    Type: AWS::Lambda::EventInvokeConfig
    Properties:
      DestinationConfig:
        OnFailure:
          Destination: !GetAtt rSQSQueue.Arn
      FunctionName: !Ref pFunctionName
      MaximumEventAgeInSeconds: 21600
      MaximumRetryAttempts: 3
      Qualifier: !GetAtt rLambdaVersion.Version
  # permission to invoke lambda from s3 bucket
  rS3InvokeLambdaPermission:
    Type: AWS::Lambda::Permission
    Properties:
      Action: lambda:InvokeFunction
      FunctionName: !GetAtt rLambdaFunction.Arn
      Principal: s3.amazonaws.com
      SourceAccount: !Ref AWS::AccountId
      SourceArn: !Sub arn:aws:s3:::${pBucketName}
  # create bucket s3 and configure event for invoke lambda
  rS3LambdaEvent:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref pBucketName
      NotificationConfiguration:
        LambdaConfigurations:
          - Event: s3:ObjectCreated:*
            Filter:
              S3Key:
                Rules:
                  - Name: prefix
                    Value: results/
                  - Name: suffix
                    Value: .csv
            Function: !GetAtt rLambdaFunction.Arn